/**
 * MCP Hook Templates
 *
 * Templates for MCP integration hooks and permissions.
 */

/**
 * MCP permissions for Graphiti tools
 */
export const graphitiPermissions = [
  'mcp__graphiti__add_memory',
  'mcp__graphiti__search_memory_facts',
  'mcp__graphiti__search_nodes',
  'mcp__graphiti__get_episodes',
  'mcp__graphiti__delete_entity_edge',
  'mcp__graphiti__delete_episode',
  'mcp__graphiti__get_entity_edge',
  'mcp__graphiti__clear_graph',
  'mcp__graphiti__get_status',
];

/**
 * MCP permissions for Serena tools
 */
export const serenaPermissions = [
  'mcp__plugin_serena_serena__activate_project',
  'mcp__plugin_serena_serena__list_dir',
  'mcp__plugin_serena_serena__find_file',
  'mcp__plugin_serena_serena__get_symbols_overview',
  'mcp__plugin_serena_serena__find_symbol',
  'mcp__plugin_serena_serena__search_for_pattern',
  'mcp__plugin_serena_serena__find_referencing_symbols',
  'mcp__plugin_serena_serena__replace_symbol_body',
  'mcp__plugin_serena_serena__insert_after_symbol',
  'mcp__plugin_serena_serena__insert_before_symbol',
  'mcp__plugin_serena_serena__rename_symbol',
  'mcp__plugin_serena_serena__write_memory',
  'mcp__plugin_serena_serena__read_memory',
  'mcp__plugin_serena_serena__list_memories',
  'mcp__plugin_serena_serena__delete_memory',
  'mcp__plugin_serena_serena__edit_memory',
];

/**
 * Get MCP permissions based on enabled integrations
 */
export function getMcpPermissions(graphiti: boolean, serena: boolean): string[] {
  const permissions: string[] = [];

  if (graphiti) {
    permissions.push(...graphitiPermissions);
  }

  if (serena) {
    permissions.push(...serenaPermissions);
  }

  return permissions;
}

import type { HooksConfig } from './settings-local.js';

/**
 * Get MCP hooks configuration for settings.local.json
 * Uses {{PROJECT_ROOT}} template variable for portability
 */
export function getMcpHooks(
  _projectPath: string, // Kept for API compatibility but not used
  graphiti: boolean,
  serena: boolean
): HooksConfig {
  const hooks: HooksConfig = {};

  // SessionStart hooks - use {{PROJECT_ROOT}} for portability
  if (graphiti || serena) {
    hooks.SessionStart = [
      {
        matcher: '.*',
        hooks: [
          {
            type: 'command',
            command: '{{PROJECT_ROOT}}/.claude/hooks/session-start-mcp.sh',
            statusMessage: 'Loading MCP integration...',
          },
        ],
      },
    ];
  }

  // Stop hooks (session end) for Graphiti
  if (graphiti) {
    hooks.Stop = [
      {
        matcher: '.*',
        hooks: [
          {
            type: 'command',
            command: '{{PROJECT_ROOT}}/.claude/hooks/session-end-graphiti.sh',
            statusMessage: 'Saving session knowledge...',
          },
        ],
      },
    ];
  }

  return hooks;
}

/**
 * Create session start hook script
 */
export function createSessionStartHook(
  graphiti: boolean,
  serena: boolean,
  graphitiGroupId: string,
  serenaProjectName: string
): string {
  const lines: string[] = [
    '#!/bin/bash',
    '# MCP Session Start Hook',
    '# Generated by Agentic Framework CLI',
    '',
    '# This hook provides reminders for MCP activation at session start',
    '',
  ];

  if (serena) {
    lines.push('# Serena activation reminder');
    lines.push('cat << \'EOF\'');
    lines.push('<system-reminder>');
    lines.push('## Serena Activation Required');
    lines.push('');
    lines.push('This project uses Serena for semantic code navigation.');
    lines.push(`Activate it now: \`activate_project("${serenaProjectName}")\``);
    lines.push('');
    lines.push('After activation, use Serena tools instead of reading full files:');
    lines.push('- `get_symbols_overview` for file structure');
    lines.push('- `find_symbol` for specific functions/classes');
    lines.push('- `search_for_pattern` for code search');
    lines.push('</system-reminder>');
    lines.push('EOF');
    lines.push('');
  }

  if (graphiti) {
    lines.push('# Graphiti context reminder');
    lines.push('cat << \'EOF\'');
    lines.push('<system-reminder>');
    lines.push('## Graphiti Memory Available');
    lines.push('');
    lines.push('This project uses Graphiti for persistent memory.');
    lines.push(`Group ID: \`${graphitiGroupId}\``);
    lines.push('');
    lines.push('Search for context:');
    lines.push(`\`search_memory_facts("project context", group_ids=["${graphitiGroupId}"])\``);
    lines.push('</system-reminder>');
    lines.push('EOF');
    lines.push('');
  }

  lines.push('exit 0');

  return lines.join('\n');
}

/**
 * Create session end hook script for Graphiti
 */
export function createSessionEndHook(graphitiGroupId: string): string {
  return `#!/bin/bash
# Graphiti Session End Hook
# Generated by Agentic Framework CLI

# This hook provides a reminder to save important learnings to Graphiti

cat << 'EOF'
<system-reminder>
## Session End - Save Learnings

Before ending this session, consider saving important discoveries to Graphiti:

\`\`\`
add_memory(
  name="Session: <topic>",
  episode_body="<key findings, decisions, or discoveries>",
  group_id="${graphitiGroupId}"
)
\`\`\`

This helps preserve context for future sessions.
</system-reminder>
EOF

exit 0
`;
}

/**
 * Generate CLAUDE.md MCP section
 */
export function generateClaudeMdMcpSection(
  graphiti: boolean,
  serena: boolean,
  graphitiGroupId: string,
  serenaProjectName: string
): string {
  const sections: string[] = [
    '## MCP Integration',
    '',
  ];

  if (graphiti && serena) {
    sections.push('This project uses Graphiti (knowledge graph) and Serena (semantic code navigation).');
  } else if (graphiti) {
    sections.push('This project uses Graphiti for persistent knowledge graph memory.');
  } else if (serena) {
    sections.push('This project uses Serena for semantic code navigation.');
  }

  sections.push('');
  sections.push('### Session Start');

  if (serena) {
    sections.push(`1. Activate Serena: \`activate_project("${serenaProjectName}")\``);
  }

  if (graphiti) {
    sections.push(`${serena ? '2' : '1'}. Search context: \`search_memory_facts("project overview", group_ids=["${graphitiGroupId}"])\``);
  }

  sections.push('');
  sections.push('### Tool Selection');
  sections.push('');
  sections.push('| Task | Use | Instead of |');
  sections.push('|------|-----|------------|');

  if (serena) {
    sections.push('| Find files | Serena `find_file` | Glob |');
    sections.push('| Search code | Serena `search_for_pattern` | Grep |');
    sections.push('| File structure | Serena `get_symbols_overview` | Read full file |');
  }

  if (graphiti) {
    sections.push('| Remember context | Graphiti `add_memory` | Notes |');
    sections.push('| Find facts | Graphiti `search_memory_facts` | Re-explore |');
  }

  sections.push('');
  sections.push('### Configuration');
  sections.push('');

  if (serena) {
    sections.push(`- **Serena Project Name:** \`${serenaProjectName}\``);
  }

  if (graphiti) {
    sections.push(`- **Graphiti Group ID:** \`${graphitiGroupId}\``);
  }

  if (serena) {
    sections.push('- **Serena Memories:** `.serena/memories/`');
  }

  return sections.join('\n');
}
