/**
 * Serena Project Configuration Template
 *
 * Generates .serena/project.yml for Serena integration.
 */

/**
 * Create Serena project configuration
 */
export function createSerenaProjectConfig(projectName: string, language: string): string {
  // Language-specific include/exclude patterns
  const patterns = getLanguagePatterns(language);

  return `# Serena Project Configuration
# Generated by Agentic Framework CLI

name: "${projectName}"
language: ${language}

# Directories to index for semantic analysis
include:
${patterns.include.map(p => `  - "${p}"`).join('\n')}

# Directories to exclude from indexing
exclude:
${patterns.exclude.map(p => `  - "${p}"`).join('\n')}

# Index configuration
index:
  # Maximum file size to index (in bytes)
  max_file_size: 1000000

  # File extensions to index (empty = use language defaults)
  extensions: []

  # Enable incremental indexing
  incremental: true

# Memory configuration
memory:
  # Directory for storing memories
  path: ".serena/memories"

  # Auto-load memories on project activation
  auto_load: true
`;
}

/**
 * Get language-specific include/exclude patterns
 */
function getLanguagePatterns(language: string): { include: string[]; exclude: string[] } {
  const commonExclude = [
    'node_modules/',
    '.git/',
    'dist/',
    'build/',
    'coverage/',
    '.next/',
    '.nuxt/',
    '__pycache__/',
    '.pytest_cache/',
    'target/',
    'vendor/',
    '.cache/',
    'tmp/',
  ];

  switch (language) {
    case 'typescript':
    case 'javascript':
      return {
        include: ['src/', 'lib/', 'app/', 'components/', 'pages/', 'test/', 'tests/'],
        exclude: [...commonExclude, '*.d.ts', '*.min.js', '*.bundle.js'],
      };

    case 'python':
      return {
        include: ['src/', 'lib/', 'app/', 'tests/', 'scripts/'],
        exclude: [...commonExclude, '*.pyc', '.venv/', 'venv/', '.tox/', 'eggs/', '*.egg-info/'],
      };

    case 'go':
      return {
        include: ['cmd/', 'pkg/', 'internal/', 'api/'],
        exclude: [...commonExclude, 'vendor/'],
      };

    case 'rust':
      return {
        include: ['src/', 'tests/', 'benches/'],
        exclude: [...commonExclude, 'target/'],
      };

    case 'java':
      return {
        include: ['src/main/', 'src/test/'],
        exclude: [...commonExclude, 'target/', '.gradle/', 'build/'],
      };

    default:
      return {
        include: ['src/', 'lib/', 'app/'],
        exclude: commonExclude,
      };
  }
}

/**
 * Validate Serena project name
 */
export function validateSerenaProjectName(name: string): boolean {
  return /^[a-zA-Z0-9_-]+$/.test(name);
}
