#!/usr/bin/env node
/**
 * Claude Folder Protection Hook
 *
 * Advisory hook that warns when editing files in protected .claude/ subdirectories.
 * These files are synced from framework modules and direct edits will be overwritten
 * when running `agentic-framework sync`.
 *
 * Protected paths (warn on edit):
 * - .claude/skills/     - Synced from framework modules
 * - .claude/commands/   - Synced from framework modules
 * - .claude/hooks/      - Synced from framework modules
 * - .claude/registries/ - Auto-generated by sync
 *
 * User-owned paths (allow edits):
 * - .claude/settings.local.json  - User customizations
 * - .claude/settings.json        - Plugin settings
 * - .claude/agents/              - Custom agent JSON configs
 * - .claude/context/             - Project-specific context files
 * - .claude/statusline.sh        - Can be customized
 */

import {
  parseHookInput,
  sendResponse,
  advisory,
  passThrough,
  type ToolInput,
  type HookMessage,
} from './types.js';

/**
 * Protected .claude/ subdirectories that are synced from framework
 */
const PROTECTED_CLAUDE_PATHS = [
  '.claude/skills/',
  '.claude/commands/',
  '.claude/hooks/',
  '.claude/registries/',
];

/**
 * Descriptions for protected paths (generic, not framework-specific)
 */
const PATH_DESCRIPTIONS: Record<string, string> = {
  '.claude/skills/': 'Skills are synced from framework modules',
  '.claude/commands/': 'Agent commands are synced from framework modules',
  '.claude/hooks/': 'Hooks are synced from framework modules',
  '.claude/registries/': 'Registries are auto-generated by sync',
};

/**
 * Check if a file path is in a protected .claude/ directory
 */
function isProtectedClaudePath(filePath: string): string | null {
  for (const protectedPath of PROTECTED_CLAUDE_PATHS) {
    if (filePath.includes(protectedPath)) {
      return protectedPath;
    }
  }
  return null;
}

/**
 * Get a helpful message about the protected path
 */
function getProtectionMessage(protectedPath: string): string {
  const description = PATH_DESCRIPTIONS[protectedPath];
  if (description) {
    return `${description}. Run "agentic-framework sync" to update from source.`;
  }
  return 'This file is managed by the framework. Run "agentic-framework sync" to update.';
}

async function main(): Promise<void> {
  try {
    const input = await parseHookInput<ToolInput>();

    // Only process Write and Edit tools
    if (!['Write', 'Edit'].includes(input.tool_name)) {
      sendResponse(passThrough());
      return;
    }

    const filePath = input.tool_input.file_path as string | undefined;

    if (!filePath) {
      sendResponse(passThrough());
      return;
    }

    // Check if file is in a protected .claude/ directory
    const protectedPath = isProtectedClaudePath(filePath);

    if (protectedPath) {
      const protectionMessage = getProtectionMessage(protectedPath);
      const messages: HookMessage[] = [
        {
          level: 'warning',
          message: `Direct edits will be overwritten. ${protectionMessage}`,
          file: filePath,
        },
      ];

      sendResponse(
        advisory(
          messages,
          'Editing synced .claude/ file - changes may be overwritten by sync'
        )
      );
      return;
    }

    // Not a protected path, pass through
    sendResponse(passThrough());
  } catch (_error) {
    // On any error, pass through to avoid blocking
    sendResponse(passThrough());
  }
}

main();
